data-finder-site/api/urls.py
from django.conf.urls import patterns, url, include
from rest_framework.urlpatterns import format_suffix_patterns
from api import views


urlpatterns = patterns('',
	 # url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),
	 url(r'^datasets/$', views.DatabaseList.as_view()),
	 url(r'^datasets/timeline-data/$', views.timeline_data, name='timeline-data'),
	 url(r'^dataset/(?P<database_id>.+)/gps-points$', views.dataset_gps_points, name='dataset-gps-points'),
	 url(r'^dataset/(?P<database_id>.+)/squared-heatmap-data$', views.dataset_squared_heatmap, name='dataset-squared-heatmap-data'),
)

urlpatterns = format_suffix_patterns(urlpatterns)

data-finder-site/data_finder/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.http import HttpResponseRedirect

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'data_finder.views.home', name='home'),
	# url(r'^blog/', include('blog.urls')),
	url(r'^', include('finder.urls', namespace="finder")),
	url(r'^api/', include('api.urls', namespace="api")),
	url(r'^admin/', include(admin.site.urls)),
    url(r'^favicon.ico/$', lambda x: HttpResponseRedirect(settings.STATIC_URL+'favicon.ico')), #google chrome favicon fix
)

data-finder-site/finder/urls.py
from django.conf.urls import patterns, url
from django.views.generic import RedirectView
from django.views import generic


from finder import views

urlpatterns = patterns('',
	# url(r'^$', views.index, name='index'),
	url(r'^$', RedirectView.as_view(url='/datasets'), name='index'),
	url(r'^overview$', views.catalog_overview, name='catalog_overview'),
	url(r'^alarms$', views.alarms, name='alarms'),
	url(r'^datasets$', views.DatabaseListView.as_view(), name='list'),
	url(r'^dataset/(?P<database_id>.+)/$', views.detail_database, name='detail-database'),
	url(r'^dataset/(?P<database_id>.+)/map$', views.detail_database_map, name='detail-database-map'),
	url(r'^dataset/(?P<database_id>.+)/data$', views.detail_database_data, name='detail-database-data'),
	url(r'^dataset/(?P<database_id>.+)/columns$', views.detail_database_columns, name='detail-database-columns'),
	url(r'^dataset/(?P<database_id>.+)/column/(?P<column_name>.+)$', views.detail_database_column, name='detail-database-column'),
	url(r'^dataset/(?P<database_id>.+)/charts$', views.detail_database_charts, name='detail-database-charts'),
	url(r'^dataset/(?P<database_id>.+)/related-datasets$', views.detail_dataset_related, name='detail-related-datasets'),
	url(r'^dataset/(?P<database_id>.+)/help$', views.detail_dataset_help, name='detail-dataset-help'),
	url(r'^dataset/(?P<database_id>.+)/(?P<tab>.+)$', views.detail_database, name='detail-database-tab'),
	url(r'^search-map/$', views.seach_map, name='search-map'),
)

data-finder-site/finder/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from django.db.models import Count, Sum, Q

from finder.models import Database, Column, Alarm, System
from profiler.models import SimpleType, DetailedType
import utils
from utils import GoogleChartsColors as GColors
from utils import TypeColors
import math
from datetime import datetime
import ast

# from django.views.decorators.cache import cache_page

def setup_filter_options(context, object_list = None):
	where_column = where = None
	ids = None
	BASE_SQL_COUNT = 'select {0}, count(distinct database_id) from finder_column where {0} is not null group by {0} order by 1'
	if object_list:
		ids = []
		# get ids from 
		for ds in object_list:
			ids.append('{0}'.format(ds.id))
		ids = ','.join(ids)
		where = 'finder_database.id in ({0})'.format( ids )
		where_column = ' database_id in ({0})'.format( ids )
		BASE_SQL_COUNT = 'select {0}, count(distinct database_id) from finder_column where {0} is not null and database_id in ({1}) group by {0} order by 1'

	context['options_category'] = utils.count_value('category', where=where)
	context['options_profiler_status'] = utils.count_value('profiler_status_short', include_nulls=False, where=where)
	context['options_source_agency'] = utils.count_value('source_agency', include_nulls=False, where=where, order_by_counts=False)
	context['options_socrata_status'] = utils.count_value('socrata_status', include_nulls=False, where=where, order_by_counts=False)
	context['simple_types'] = utils.execute_query(BASE_SQL_COUNT.format('profiler_type', ids))
	context['detailed_types'] = utils.execute_query(BASE_SQL_COUNT.format('profiler_type_most_detected', ids))
	context['options_socrata_type'] = utils.execute_query(BASE_SQL_COUNT.format('socrata_type', ids))
	context['options_update_frequency'] = utils.count_value('socrata_update_frequency', where=where, order_by_counts=False)



def filter_datasets_with_params(request, context, queryset=None):
	if queryset is None: queryset = Database.objects.all()

	# Category
	param = request.GET.get('category', None)
	if param is not None: 
		if param == 'None': queryset = queryset.filter(category__isnull=True)
		else: queryset = queryset.filter(category=param)
	
	# Source/Agency
	param = request.GET.get('agency', None)
	if param is not None: 
		if param == 'None': queryset = queryset.filter(source_agency__isnull=True)
		else: queryset = queryset.filter(source_agency=param)

	# Update Frequency
	param = request.GET.get('update_frequency', None)
	if param is not None: 
		if param == 'None': queryset = queryset.filter(socrata_update_frequency__isnull=True)
		else: queryset = queryset.filter(socrata_update_frequency=param)

	# Profiler Status
	param = request.GET.get('profiler_status', 'OK')
	# print 'profiler status= "'+ param + '"'
	if param is not None: 
		param = param.split('\n')[0]
		queryset = queryset.filter( Q(profiler_status_short=param) | Q(profiler_status__like=param+'%') )

	# Socrata Primary
	param = request.GET.get('primary', None)
	if param is not None: queryset = queryset.filter(socrata_primary=param=='True')

	# Original Column
	param = request.GET.get('column_original', None)
	if param is not None: queryset = queryset.filter(socrata_primary=param=='True')


	# Column Type = Simple or Detailed
	param = request.GET.get('column_type', None)
	if param == 'Geo-ZIP 4': param = 'Geo-ZIP+4' ##TODO: Fix this on the right way.
	if param is not None: queryset = queryset.filter(
													Q(column__profiler_type=param) |  
													Q(column__profiler_type_most_detected=param)
													)
	
	# Provided Type
	param = request.GET.get('provided_type', None)
	if param is not None: queryset = queryset.filter( Q(column__socrata_type=param) )

	# Socrata Status
	DEFAULT = -1
	param = request.GET.get('metadata_retrieval_status', DEFAULT)
	if param != DEFAULT and param is not None: queryset = queryset.filter(socrata_status__isnull=False, socrata_status=param )
	elif param is None: queryset = queryset.filter( socrata_status__isnull=True )

	# Text filter: Database Id, Name, tags, description, etc...
	param = request.GET.get('search_text', None)
	if param: 
		#split param and gerate or statements
		param_list = param.split(' ')
		text_search_filters = None
		
		for a_param in param_list:
			one_filter = Q(database_id__icontains=a_param) | Q(name__icontains=a_param) | \
							Q(description__icontains=a_param) | Q(category__icontains=a_param) | \
							Q(tags__icontains=a_param) | Q(source_agency__icontains=a_param) | \
							Q(column__name__icontains=a_param) 

			if text_search_filters is None: text_search_filters = one_filter
			else: text_search_filters |= one_filter
		queryset = queryset.filter(text_search_filters)

	# geo_zipcode
	param = request.GET.get('zipcode', None)
	if param is not None: queryset = queryset.filter(gpsdata__zipcode=param)

	# date_range
	param = request.GET.get('date_range', None)
	# print 'param=', param
	if param is not None: 
		start, end = param.split('-')
		if start:
			start = datetime.strptime(start, '%m/%d/%Y')
			queryset = queryset.filter(date_max__gte=start)
		if end:
			end = datetime.strptime(end, '%m/%d/%Y')
			queryset = queryset.filter(date_min__lte=end)
		
	date_range = param or '-'

	# print '>>> queryset.query=', queryset.query

	#Order by download counts
	queryset = queryset.order_by('-socrata_download_count', 'name', 'database_id')
	queryset = queryset.extra(select={'socrata_download_count_null':'socrata_download_count is null'})
	queryset = queryset.extra(order_by = ['socrata_download_count_null'])
	
	results = queryset.distinct()
	ds_ids = []
	for ds in results:
		ds_ids.append(ds.database_id)
	
	#Setup the timeline api query params
	if context is not None: 
		api_timeline_query = ''
		if date_range: api_timeline_query += '?date_range={0}'.format(date_range)
		if len(ds_ids) > 0: api_timeline_query += '&dataset_ids={0}'.format(ds_ids)
		context['api_timeline_query'] = api_timeline_query
	return results


def seach_map(request):
	context = {}
	queryset = Database.objects.exclude(lat_min = None, lat_max = None, long_min = None, long_max = None).order_by('lat_min', '-lat_max','database_id')
	queryset = filter_datasets_with_params(request, context, queryset)
	datasets = queryset.all()
	context['databaseBoundingBoxes'] = datasets
	setup_filter_options(context, datasets)

	#Display map style
	map_type = request.GET.get('map_style', 'boxes')
	if map_type is not None:
		if map_type == 'borough':
			areas = utils.execute_query("select boroname, ST_AsGeoJSON(geom) from nyc_boroughs")
			named_areas = []
		
			for area in areas:
				named_areas.append({'title': area[0].encode('ascii','ignore'),
									'geojson': ast.literal_eval(area[1])})
			context['named_areas'] = named_areas
			context['map_center'] = 'NYC'
		elif map_type == 'single-heatmap':
			# ids = Database.objects.filter(category='Education').values_list('id', flat=True).order_by('id')
			ids = queryset.values_list('id', flat=True).order_by('id')
			gps_data = utils.execute_query('select lat::float, long::float, sum(count)::int from finder_gpsdata where lat is not null and database_id in ({0}) group by lat, long '.format( str(ids[:10])[1:-1] ))
			
			context['gps_data'] = gps_data
			print 'dbs=', len(ids)
			print 'gps_data=', len(gps_data)


	context['map_style'] = map_type

	return render(request, 'finder/search-map.html', context)


class DatabaseListView(generic.ListView):	
	model = Database
	template_name = 'finder/list.html'
	context_object_name = 'databases'
	paginate_by = 50

	def get_queryset(self):
		queryset = filter_datasets_with_params(self.request, None)
		self.total = queryset.count()

		return queryset

	def get_context_data(self, **kwargs):
		context = super(DatabaseListView, self).get_context_data(**kwargs)

		context['query_result_count'] = self.total
		object_list = context['object_list']
		setup_filter_options(context, object_list=self.object_list)

		return context

	# def dispatch(self, request, *args, **kwargs):
	# 	queryset = self.get_queryset()
	# 	if queryset.count() == 1:
	# 		return redirect('detail-database', database_id=queryset.only('id')[0])
	# 	else:
	# 		return super(DatabaseListView, self).dispatch(request, *args, **kwargs)

	
# @cache_page(60 * 15) #Cache for 15 minutes
def catalog_overview(request):
	context = {}

	if Database.objects.count() > 0: context['chart_list'] = [
				 	{ 'title':'Dataset Categories', 
						'data': utils.count_as_json('category', order_by_counts=False),
						'colors':GColors.PALLETE},
					{ 'title':'Rows by Category', 
						'data': utils.execute_query_as_json('select category, sum(rows) from finder_database where profiler_status = \'OK\' and category is not null group by category order by 1'),
						'colors':GColors.PALLETE},
					{ 'title':'Datasets w/ Geo Data', 
						'data': utils.execute_query_as_json( utils.sql_count_null_or_not_null('columns_geo_count', label_not_null='Have', label_null='Don`t Have'), sort=False),
						'colors': [GColors.BLUE,  GColors.RED] },
					{ 'title':'Datasets with GPS', 
						'data': utils.execute_query_as_json( utils.sql_count_null_or_not_null('gps_values', label_not_null='Have', label_null='Don`t Have'), sort=False),
						'colors': [GColors.BLUE,  GColors.RED] },
					{ 'title':'Datasets w/ Temp. Data', 
						'data': utils.execute_query_as_json( utils.sql_count_null_or_not_null('columns_temporal_count', label_not_null='Have', label_null='Don`t Have'), sort=False),
						'colors': [GColors.BLUE,  GColors.RED] },
					{ 'title':'Datasets w/ Num. Data', 
						'data': utils.execute_query_as_json( utils.sql_count_null_or_not_null('columns_numeric_count', label_not_null='Have', label_null='Don`t Have'), sort=False),
						'colors': [GColors.BLUE,  GColors.RED] },
					{ 'title':'Datasets w/ Text. Data', 

data-finder-site/finder/templates/finder/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!--meta http-equiv="X-UA-Compatible" content="IE=edge"-->
    <!--meta name="viewport" content="width=device-width, initial-scale=1"-->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Home{% endblock title %} @ Urban Profiler</title>

    {% load staticfiles %}
    {% load finder_extras %}

    <link rel="stylesheet" type="text/css" href="{% static 'finder/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap-theme.css' %}" />

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'jquery/1.11.3/jquery-1.11.3.min.js' %}"></script>

    <script src="{% static 'finder/helpers.js' %}"></script>

    <!-- Bootstrap core JavaScript
    ================================================== -->

</head>

<body>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <!--      NAVIGATION BAR              -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div id='logos'>
            <img src="{% static 'images/cusp-index.png' %}" id="logo-cusp">
        </div>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand">Urban Profiler</a>
        <div >
            <img src="{% static 'images/beta-ribbon.png' %}" id="beta-ribbon">
        </div>
        <!--<a class="navbar-brand" href="{% url 'finder:catalog_overview' %}">Data Finder</a>-->
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'finder:list' %}">Datasets</a></li>
        <li><a href="{% url 'finder:search-map' %}">Search Map</a></li>
        
        <li><a href="{% url 'finder:alarms' %}">Alarms</a></li>
        <li><a href="{% url 'finder:catalog_overview' %}">Overview</a></li>
        {% if 'DEVELOPMENT'|is_current_env %}
        <li><a href="{% url 'admin:index' %}">Admin</a></li>
        {% endif %}
    </ul>
</div>
<!--/.nav-collapse -->
</div>
</nav>

<!--      CONTENT              -->
<div class="container" id="content">
    {% if error_message %}
    <div class="alert alert-danger" role="alert"><b>Oh, no! We found a problem! </b>{{ error_message }}</div>
    {% endif %}

    {% block content %}{% endblock content %}

    {% if is_paginated %}
    <!-- .... **Now the pagination section** .... -->
    <div class="pagination center-block">
        <span class="page-links">
            {% if page_obj.has_previous %}
            <a href="{% url_add_query page=page_obj.previous_page_number %}">previous</a>
            {% endif %}
            <span class="page-current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
            <a href="{% url_add_query page=page_obj.next_page_number %}">next</a>
            {% endif %}
        </span>
    </div>
    {% endif %}
</div>


    <!--
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
-->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

{% block scripts %}{% endblock scripts %}

<script>   
    //Dont let modals close without x buton.
    // $('div.modal').attr("data-backdrop","static");
    // $('div.modal').attr("data-keyboard", "false");
    var url = window.location;
    // Will only work if string in href matches with location
    $('ul.nav a[href="'+ url +'"]').parent().addClass('active');

    // Will also work for relative and absolute hrefs
    $('ul.nav a').filter(function() {
        return this.href == url;
    }).parent().addClass('active');
    </script>   

    <!-- Google Analytics -->
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-65529543-1', 'auto');
  ga('send', 'pageview');

  </script>
</body>
</html>

data-finder-site/finder/templates/finder/detail.html
{% extends "finder/base.html" %}
{% block title %}{{ db.database_id }} 
Details
{% endblock title%}
{% load staticfiles %}


{% block content %}

<h1>{{ db.name|default:db.database_id }}

  <div class="pull-right highlight" id="dataset-actions">
    <small>
      {# <span class="glyphicon glyphicon-exclamation-sign gray" aria-hidden="true"></span> #}
      <!-- Links -->
      {% if db.hue_url %}
      <a target="_blank" href="{{db.hue_url}}">
        <img class='hue-logo' src="{% static 'images/hue-logo-mini-white.png' %}" id="logo-hue" data-toggle="tooltip" data-placement="top" title="Explore on Hue"/>
      </a>
      {% elif db.show_input_file %}
      <a target="_blank" href="https://nycopendata.socrata.com/-/-/{{db.database_id}}"><span class="glyphicon glyphicon-eye-open" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="View dataset"/></a>
      {% endif %}

      {% if db.show_input_file %}
      <a href="https://nycopendata.socrata.com/api/views/{{db.database_id}}/rows.csv?accessType=DOWNLOAD"><span class="glyphicon glyphicon-download-alt" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Download CSV"/></a>
      {% else %}
      <a><span class="red glyphicon glyphicon-lock" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="This dataset is not open."/></a>

      {% endif %}
    </small>
  </div>

</h1>
{% if db.description %}
<div class="row">
  <div class="col-md-12">
    <h4> {{ db.description }} </h4>
  </div>
</div>
{% endif %}

<ul class="nav nav-tabs">
  <li {% if tab == 'data' %} class="active" {% endif %}><a href="{% url 'finder:detail-database-data' db.database_id %}"> 
    <span class="glyphicon glyphicon-qrcode" aria-hidden="true"></span> Metadata</a>
  </li>

  {% if db.columns_count > 0 %}<li {% if tab == 'columns' %} class="active" {% endif %}><a href="{% url 'finder:detail-database-columns' db.database_id %}">
  <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> 
  {{columns_count}} Column{{columns_count|pluralize}}</a>
</li>{% endif %}

{% if db.profiler_status == 'OK' %}<li {% if tab == 'charts' %} class="active"{% endif %}><a href="{% url 'finder:detail-database-charts' db.database_id %}"> 
<span class="glyphicon glyphicon-stats" aria-hidden="true"></span> Charts</a>
</li>{% endif %}

{% if db.gps_values > 0 %}
<li {% if tab == 'map' %} class="active"{% endif %}><a href="{% url 'finder:detail-database-map' db.database_id%}">  
  <span class="glyphicon glyphicon-globe" aria-hidden="true"></span> Map</a>
</li>
{% endif %}

<li {% if tab == 'related-datasets' %} class="active"{% endif %}><a href="{% url 'finder:detail-related-datasets' db.database_id %}"> 
  <span class="glyphicon glyphicon-link" aria-hidden="true"></span> Related Datasets</a>
</li>

<li {% if tab == 'dataset-help' %} class="active"{% endif %}><a href="{% url 'finder:detail-dataset-help' db.database_id %}"> 
  <span class="glyphicon glyphicon-flash" aria-hidden="true"></span> Code Snippets </a>
</li>

</ul>

{% if tab == 'map' %}
{% include "finder/includes/tab_detail_map.html" %}

{% elif tab == 'charts' %}
{% include "finder/includes/tab_detail_charts.html" %}

{% elif tab == 'columns' %}
{% include "finder/includes/tab_detail_columns.html" %}

{% elif tab == 'related-datasets' %}
{% include "finder/includes/tab_related_datasets.html" %}

{% elif tab == 'dataset-help' %}
{% include "finder/includes/tab_dataset_helps.html" %}

{% else %} <!-- default tab -->
{% include "finder/includes/tab_detail_data.html" %}
{% endif %}

{% endblock content %}

data-finder-site/finder/templates/finder/list.html
{% extends "finder/base.html" %}
{% block title %}Datasets{% endblock %}

{% load finder_extras %}
{% load humanize %}

{% block content %}
<div class="row">
	<div class="col-sm-6 col-md-6 col-lg-3  filters-col">
		<!-- ################# Filters ################# -->
		{% include "finder/includes/datasets_filter_side_bar.html" %}
	</div> <!-- Column content-filters -->

	<div class="col-sm-6 col-md-6 col-lg-9 ">
		{% if databases %}
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title"> 
					<strong> Datasets <span class="badge">{{ query_result_count }}</span> </strong>
					{% if is_paginated %}
					<small>
						<div class="right">
							<span class="page-links">
								{% if page_obj.has_previous %}
								<a href="{% url_add_query page=page_obj.previous_page_number %}">previous</a>
								{% endif %}
								<span class="page-current">
									Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
								</span>
								{% if page_obj.has_next %}
								<a href="{% url_add_query page=page_obj.next_page_number %}">next</a>
								{% endif %}
							</span>
						</div>
					</small>
					{% endif %}
				</h3>
			</div>
			<div class="panel-body">
				<!-- TABLE -->
				<div class="col-md-12">
					<table class="table table-striped table-hover tablesorter">
						<thead> <tr></tr> </thead>
						<tbody>
							{% for db in databases %}
							<tr>
								<td>
									<!-- Title, Agency and Description -->
									<b><a href="{% url 'finder:detail-database' db.database_id %}" 
										{% if db.category %}
										data-toggle="tooltip" data-placement="right" title="Category: {{db.category}}
										{{ db.columns_count|intcomma }} column{{db.columns_count|pluralize}} and {{ db.rows|intcomma }} row{{db.rows|pluralize}} ({{ db.missing_percent|floatformat}}% missing)"
										{% endif %}
										/>{{db.name|default:db.database_id}}</a>
										{% if  db.socrata_status_error %} <span class="glyphicon glyphicon-import red" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="There was an error retrieving metadata for this dataset."></span> {% endif %}

										{% if  db.profiler_status_error %} <span class="glyphicon glyphicon-expand red" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="There was an error profiling this dataset."></span> {% endif %}

										<div  class="pull-right">
											{% if db.gps_values > 0 %}<a href="{% url 'finder:detail-database-map' db.database_id%}"><span class="glyphicon glyphicon-globe" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="View on Map"></span></a>{%endif%}
											<a href="{% url 'finder:detail-database-data' db.database_id %}"><span class="glyphicon glyphicon-search" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Explore Details"></span></a>
											<a href="{% url 'finder:detail-database-charts' db.database_id %}"><span class="glyphicon glyphicon-stats" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Charts"></span></a>
											<a target="_blank" href="https://nycopendata.socrata.com/-/-/{{db.database_id}}"><span class="glyphicon glyphicon-eye-open" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="View dataset"/></a>
											<a href="https://nycopendata.socrata.com/api/views/{{db.database_id}}/rows.csv?accessType=DOWNLOAD"><span class="glyphicon glyphicon-download-alt" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Download"/></a>
										</div>
										{% if db.source_agency %} <br/> {{db.source_agency}} {% endif %} </b>
									</br>
									{{db.description|default_if_none:''}}

								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div> <!-- Column -->
			</div> <!-- Panel Body -->
		</div> <!-- Panel -->
	</div> <!-- row -->

	{% else %}
	<div class="alert alert-danger" role="alert">
		<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
		<span class="sr-only">Error:</span>
		No Datasets available or no dataset found with desired filter. 
		Please try another filter.
	</div>
	{% endif %}
</div> <!-- Column content-filters -->



{% endblock %}


{% block scripts %}
<script>
$(function () {
	$('[data-toggle="tooltip"]').tooltip()
})
</script>

{% endblock scripts %}