data-finder-site/api/urls.py
from django.conf.urls import patterns, url, include
from rest_framework.urlpatterns import format_suffix_patterns
from api import views


urlpatterns = patterns('',
	 # url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),
	 url(r'^datasets/$', views.DatabaseList.as_view()),
	 url(r'^datasets/timeline-data/$', views.timeline_data, name='timeline-data'),
	 url(r'^dataset/(?P<database_id>.+)/gps-points$', views.dataset_gps_points, name='dataset-gps-points'),
	 url(r'^dataset/(?P<database_id>.+)/squared-heatmap-data$', views.dataset_squared_heatmap, name='dataset-squared-heatmap-data'),
)

urlpatterns = format_suffix_patterns(urlpatterns)

data-finder-site/data_finder/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.http import HttpResponseRedirect

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'data_finder.views.home', name='home'),
	# url(r'^blog/', include('blog.urls')),
	url(r'^', include('finder.urls', namespace="finder")),
	url(r'^api/', include('api.urls', namespace="api")),
	url(r'^admin/', include(admin.site.urls)),
    url(r'^favicon.ico/$', lambda x: HttpResponseRedirect(settings.STATIC_URL+'favicon.ico')), #google chrome favicon fix
)

data-finder-site/finder/urls.py
from django.conf.urls import patterns, url
from django.views.generic import RedirectView
from django.views import generic


from finder import views

urlpatterns = patterns('',
	# url(r'^$', views.index, name='index'),
	url(r'^$', RedirectView.as_view(url='/datasets'), name='index'),
	url(r'^overview$', views.catalog_overview, name='catalog_overview'),
	url(r'^alarms$', views.alarms, name='alarms'),
	url(r'^datasets$', views.DatabaseListView.as_view(), name='list'),
	url(r'^dataset/(?P<database_id>.+)/$', views.detail_database, name='detail-database'),
	url(r'^dataset/(?P<database_id>.+)/map$', views.detail_database_map, name='detail-database-map'),
	url(r'^dataset/(?P<database_id>.+)/data$', views.detail_database_data, name='detail-database-data'),
	url(r'^dataset/(?P<database_id>.+)/columns$', views.detail_database_columns, name='detail-database-columns'),
	url(r'^dataset/(?P<database_id>.+)/column/(?P<column_name>.+)$', views.detail_database_column, name='detail-database-column'),
	url(r'^dataset/(?P<database_id>.+)/charts$', views.detail_database_charts, name='detail-database-charts'),
	url(r'^dataset/(?P<database_id>.+)/related-datasets$', views.detail_dataset_related, name='detail-related-datasets'),
	url(r'^dataset/(?P<database_id>.+)/help$', views.detail_dataset_help, name='detail-dataset-help'),
	url(r'^dataset/(?P<database_id>.+)/(?P<tab>.+)$', views.detail_database, name='detail-database-tab'),
	url(r'^search-map/$', views.seach_map, name='search-map'),
)

data-finder-site/finder/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from django.db.models import Count, Sum, Q

from finder.models import Database, Column, Alarm, System
from profiler.models import SimpleType, DetailedType
import utils
from utils import GoogleChartsColors as GColors
from utils import TypeColors
import math
from datetime import datetime
import ast

# from django.views.decorators.cache import cache_page

def setup_filter_options(context, object_list = None):
	where_column = where = None
	ids = None
	BASE_SQL_COUNT = 'select {0}, count(distinct database_id) from finder_column where {0} is not null group by {0} order by 1'
	if object_list:
		ids = []
		# get ids from 
		for ds in object_list:
			ids.append('{0}'.format(ds.id))
		ids = ','.join(ids)
		where = 'finder_database.id in ({0})'.format( ids )
		where_column = ' database_id in ({0})'.format( ids )
		BASE_SQL_COUNT = 'select {0}, count(distinct database_id) from finder_column where {0} is not null and database_id in ({1}) group by {0} order by 1'

	context['options_category'] = utils.count_value('category', where=where)
	context['options_profiler_status'] = utils.count_value('profiler_status_short', include_nulls=False, where=where)
	context['options_source_agency'] = utils.count_value('source_agency', include_nulls=False, where=where, order_by_counts=False)
	context['options_socrata_status'] = utils.count_value('socrata_status', include_nulls=False, where=where, order_by_counts=False)
	context['simple_types'] = utils.execute_query(BASE_SQL_COUNT.format('profiler_type', ids))
	context['detailed_types'] = utils.execute_query(BASE_SQL_COUNT.format('profiler_type_most_detected', ids))
	context['options_socrata_type'] = utils.execute_query(BASE_SQL_COUNT.format('socrata_type', ids))
	context['options_update_frequency'] = utils.count_value('socrata_update_frequency', where=where, order_by_counts=False)



def filter_datasets_with_params(request, context, queryset=None):
	if queryset is None: queryset = Database.objects.all()

	# Category
	param = request.GET.get('category', None)
	if param is not None: 
		if param == 'None': queryset = queryset.filter(category__isnull=True)
		else: queryset = queryset.filter(category=param)
	
	# Source/Agency
	param = request.GET.get('agency', None)
	if param is not None: 
		if param == 'None': queryset = queryset.filter(source_agency__isnull=True)
		else: queryset = queryset.filter(source_agency=param)

	# Update Frequency
	param = request.GET.get('update_frequency', None)
	if param is not None: 
		if param == 'None': queryset = queryset.filter(socrata_update_frequency__isnull=True)
		else: queryset = queryset.filter(socrata_update_frequency=param)

	# Profiler Status
	param = request.GET.get('profiler_status', 'OK')
	# print 'profiler status= "'+ param + '"'
	if param is not None: 
		param = param.split('\n')[0]
		queryset = queryset.filter( Q(profiler_status_short=param) | Q(profiler_status__like=param+'%') )

	# Socrata Primary
	param = request.GET.get('primary', None)
	if param is not None: queryset = queryset.filter(socrata_primary=param=='True')

	# Original Column
	param = request.GET.get('column_original', None)
	if param is not None: queryset = queryset.filter(socrata_primary=param=='True')


	# Column Type = Simple or Detailed
	param = request.GET.get('column_type', None)
	if param == 'Geo-ZIP 4': param = 'Geo-ZIP+4' ##TODO: Fix this on the right way.
	if param is not None: queryset = queryset.filter(
													Q(column__profiler_type=param) |  
													Q(column__profiler_type_most_detected=param)
													)
	
	# Provided Type
	param = request.GET.get('provided_type', None)
	if param is not None: queryset = queryset.filter( Q(column__socrata_type=param) )

	# Socrata Status
	DEFAULT = -1
	param = request.GET.get('metadata_retrieval_status', DEFAULT)
	if param != DEFAULT and param is not None: queryset = queryset.filter(socrata_status__isnull=False, socrata_status=param )
	elif param is None: queryset = queryset.filter( socrata_status__isnull=True )

	# Text filter: Database Id, Name, tags, description, etc...
	param = request.GET.get('search_text', None)
	if param: 
		#split param and gerate or statements
		param_list = param.split(' ')
		text_search_filters = None
		
		for a_param in param_list:
			one_filter = Q(database_id__icontains=a_param) | Q(name__icontains=a_param) | \
							Q(description__icontains=a_param) | Q(category__icontains=a_param) | \
							Q(tags__icontains=a_param) | Q(source_agency__icontains=a_param) | \
							Q(column__name__icontains=a_param) 

			if text_search_filters is None: text_search_filters = one_filter
			else: text_search_filters |= one_filter
		queryset = queryset.filter(text_search_filters)

	# geo_zipcode
	param = request.GET.get('zipcode', None)
	if param is not None: queryset = queryset.filter(gpsdata__zipcode=param)

	# date_range
	param = request.GET.get('date_range', None)
	# print 'param=', param
	if param is not None: 
		start, end = param.split('-')
		if start:
			start = datetime.strptime(start, '%m/%d/%Y')
			queryset = queryset.filter(date_max__gte=start)
		if end:
			end = datetime.strptime(end, '%m/%d/%Y')
			queryset = queryset.filter(date_min__lte=end)
		
	date_range = param or '-'

	# print '>>> queryset.query=', queryset.query

	#Order by download counts
	queryset = queryset.order_by('-socrata_download_count', 'name', 'database_id')
	queryset = queryset.extra(select={'socrata_download_count_null':'socrata_download_count is null'})
	queryset = queryset.extra(order_by = ['socrata_download_count_null'])
	
	results = queryset.distinct()
	ds_ids = []
	for ds in results:
		ds_ids.append(ds.database_id)
	
	#Setup the timeline api query params
	if context is not None: 
		api_timeline_query = ''
		if date_range: api_timeline_query += '?date_range={0}'.format(date_range)
		if len(ds_ids) > 0: api_timeline_query += '&dataset_ids={0}'.format(ds_ids)
		context['api_timeline_query'] = api_timeline_query
	return results


def seach_map(request):
	context = {}
	queryset = Database.objects.exclude(lat_min = None, lat_max = None, long_min = None, long_max = None).order_by('lat_min', '-lat_max','database_id')
	queryset = filter_datasets_with_params(request, context, queryset)
	datasets = queryset.all()
	context['databaseBoundingBoxes'] = datasets
	setup_filter_options(context, datasets)

	#Display map style
	map_type = request.GET.get('map_style', 'boxes')
	if map_type is not None:
		if map_type == 'borough':
			areas = utils.execute_query("select boroname, ST_AsGeoJSON(geom) from nyc_boroughs")
			named_areas = []
		
			for area in areas:
				named_areas.append({'title': area[0].encode('ascii','ignore'),
									'geojson': ast.literal_eval(area[1])})
			context['named_areas'] = named_areas
			context['map_center'] = 'NYC'
		elif map_type == 'single-heatmap':
			# ids = Database.objects.filter(category='Education').values_list('id', flat=True).order_by('id')
			ids = queryset.values_list('id', flat=True).order_by('id')
			gps_data = utils.execute_query('select lat::float, long::float, sum(count)::int from finder_gpsdata where lat is not null and database_id in ({0}) group by lat, long '.format( str(ids[:10])[1:-1] ))
			
			context['gps_data'] = gps_data
			print 'dbs=', len(ids)
			print 'gps_data=', len(gps_data)


	context['map_style'] = map_type

	return render(request, 'finder/search-map.html', context)


class DatabaseListView(generic.ListView):	
	model = Database
	template_name = 'finder/list.html'
	context_object_name = 'databases'
	paginate_by = 50

	def get_queryset(self):
		queryset = filter_datasets_with_params(self.request, None)
		self.total = queryset.count()

		return queryset

	def get_context_data(self, **kwargs):
		context = super(DatabaseListView, self).get_context_data(**kwargs)

		context['query_result_count'] = self.total
		object_list = context['object_list']
		setup_filter_options(context, object_list=self.object_list)

		return context

	# def dispatch(self, request, *args, **kwargs):
	# 	queryset = self.get_queryset()
	# 	if queryset.count() == 1:
	# 		return redirect('detail-database', database_id=queryset.only('id')[0])
	# 	else:
	# 		return super(DatabaseListView, self).dispatch(request, *args, **kwargs)

	
# @cache_page(60 * 15) #Cache for 15 minutes
def catalog_overview(request):
	context = {}

	if Database.objects.count() > 0: context['chart_list'] = [
				 	{ 'title':'Dataset Categories', 
						'data': utils.count_as_json('category', order_by_counts=False),
						'colors':GColors.PALLETE},
					{ 'title':'Rows by Category', 
						'data': utils.execute_query_as_json('select category, sum(rows) from finder_database where profiler_status = \'OK\' and category is not null group by category order by 1'),
						'colors':GColors.PALLETE},
					{ 'title':'Datasets w/ Geo Data', 
						'data': utils.execute_query_as_json( utils.sql_count_null_or_not_null('columns_geo_count', label_not_null='Have', label_null='Don`t Have'), sort=False),
						'colors': [GColors.BLUE,  GColors.RED] },
					{ 'title':'Datasets with GPS', 
						'data': utils.execute_query_as_json( utils.sql_count_null_or_not_null('gps_values', label_not_null='Have', label_null='Don`t Have'), sort=False),
						'colors': [GColors.BLUE,  GColors.RED] },
					{ 'title':'Datasets w/ Temp. Data', 
						'data': utils.execute_query_as_json( utils.sql_count_null_or_not_null('columns_temporal_count', label_not_null='Have', label_null='Don`t Have'), sort=False),
						'colors': [GColors.BLUE,  GColors.RED] },
					{ 'title':'Datasets w/ Num. Data', 
						'data': utils.execute_query_as_json( utils.sql_count_null_or_not_null('columns_numeric_count', label_not_null='Have', label_null='Don`t Have'), sort=False),
						'colors': [GColors.BLUE,  GColors.RED] },
					{ 'title':'Datasets w/ Text. Data', 

data-finder-site/finder/templates/finder/includes/loading.html
<div class="container">
	<button class="btn btn-lg btn-warning"><span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> {{message|default_if_none:'Loading...'}}</button>
</div>

data-finder-site/finder/templates/finder/includes/modal_big_chart.html
{% load i18n %}
{% load humanize %}
{% load finder_extras %}
<div style="position:absolute; top:0px; right:0px">
	<a><span class="blue glyphicon glyphicon-zoom-in" aria-hidden="true" data-toggle="modal" data-target="#modal_big_chart_{{id}}"></span></a>

	<!-- Modal Big Chart-->
	<div class="modal fade bs-example-modal-lg close-by-button-only" id="modal_big_chart_{{id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"> 
		<div class="modal-dialog-lg"  style="width:1200px">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<h4 class="modal-title" id="myModalLabel">{{chart.title|default:'Chart Details'}}</h4>
				</div>

				<div class="modal-body">
					<div class="container center-block">
						<div class="row">
							{% include "finder/includes/google_chart.html" with id="big_chart_"|concat:id data=chart.full_data|default:chart.data colors=chart.colors title=chart.title width=1150 height=600 type=chart.type%}
						</div>
						<div class="row center-block">
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<h4 class='page-header'> Chart Data </h4>
								<table class=" table table-striped ">
									<tbody>
										{% for data in chart.full_data|default:chart.data|eval %}
										<tr><th>{{data.0}}</th> <td>{{data.1}}</td></tr>
										{% endfor %}
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

data-finder-site/finder/templates/finder/includes/modal_filter_by_date_range.html
{% load staticfiles %}
<script src="{% static 'bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>

<!-- ref of bootstrap-datepicker:
http://eternicode.github.io/bootstrap-datepicker/?markup=range&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&todayBtn=linked&clearBtn=true&language=en&orientation=auto&multidate=&multidateSeparator=&todayHighlight=on&keyboardNavigation=on#sandbox
-->
<div class="modal fade" id="modal_filter_by_date" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Date Filter</h4>
			</div>
			<div class="modal-body">
				<div id='date-picker-container'>
					<!-- Date-Picker -->
					<div class="input-daterange input-group" id="datepicker">
						<input id="input-start" type="text" class="input-sm form-control" name="start" placeholder="mm/dd/yyyy"/>
						<span class="input-group-addon">to</span>
						<input id="input-end" type="text" class="input-sm form-control" name="end" placeholder="mm/dd/yyyy"/>
					</div>
						<input id="input-hidden-start" type="hidden"/>
						<input id="input-hidden-end" type="hidden"/>
					<!-- /Date-Picker -->
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
				<button type="button" class="btn btn-info" onclick="filterByDate()">Filter</button>
			</div>
		</div>
	</div>
</div>
<script>
$('#date-picker-container .input-daterange').datepicker({
	// format: "yyyy/mm/dd",
	// startDate: "2000/01/01",
	// endDate:"2016/01/01",
	immediateUpdates:true,
	// keyboardNavigation:false,
	// todayBtn: "linked",
	clearBtn: true,
	// forceParse: false,
	todayHighlight: true
});

function filterByDate(){
	console.log("filterByDate");
	var start = $('#input-start').val();
	var end = $('#input-end').val();

	dateRange = start + '-' + end;
	url = updateQueryStringParameter(window.location.href, 'date_range', dateRange);
}
$(document).ready(function(){
	var dateRange = getQueryStringParameter('date_range');
	var dates = dateRange.split('-');
	$('#input-start').val(dates[0]);
	$('#input-end').val(dates[1]);
});
</script>

data-finder-site/finder/templates/finder/includes/tab_detail_columns.html
{% load humanize %}
{% load finder_extras%}

{% if not columns or columns|length_is:"0" %}
<div class="alert alert-danger" role="alert">
	<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
	No Column Data found
</div>
{% else %}
<div class="container">
	{% if column %}
		<h2 class="page-header"> {{column.name}}
		<div class="dropdown pull-right">
			<button class="btn btn-default dropdown-toggle" type="button" id="dropdownColumns" data-toggle="dropdown" aria-expanded="true">
				Change Column
				<span class="caret"></span>
			</button>
			<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
				{% for a_column in columns %}
				{% if a_column.name == column.name %}
				<li role="presentation" class="active"><a data-toggle="tooltip" data-placement="left" title="Selected">{{a_column.name}}</a></li>
				{% else %}
				<li role="presentation"><a href="{% url 'finder:detail-database-column' db.database_id a_column.name %}">{{a_column.name}}</a></li>
				{% endif %}
				{% endfor %}
				<li role="presentation"><a href="{% url 'finder:detail-database-tab' db.database_id 'columns'%}" >All - Return to Column List</a></li>
			</ul>
		</div>
		</h2>
		{% include "finder/includes/column_info.html" with column=column db=db id='details'%}

	{% else %} <!-- Not detailing any column -->
	<table class="table table-striped table-hover">
		<head> <tr> 
			<th> Name </th> 
			
			<th> Provided Type 
				<span class="glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="top" title="Extracted from Metadata Source (when available)"/>
			</th> 
			<th> Type 
				<span class="glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="top" title="Type identified by Profiler"/>
			</th> 
			<th> Most Detected Type 
				<span class="glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="top" title="To view details of detected types click on magnifying glass."/>
			</th> 
			<!-- <th> Unique Values 
				<span class="glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="top" title="Proportion calculated considering only valid values."/>
			</th>  -->
			<th> Missing </th> 
			<th> Details </th> 
		</tr> </head> 
		<tbody>
			{% for column in columns %}
			<tr {% if column.name == db.socrata_unique_key %} class="info" {%endif%}> 
				<td>
					{% if column.name == db.socrata_unique_key %}
					<span class="glyphicon glyphicon-lock" data-toggle="tooltip" data-placement="top" title="Unique Key indicated by Socrata."></span>
					{% endif %}
					<a href="{% url 'finder:detail-database-column' db.database_id|escape_url column.name|escape_url %}">{{ column.name }}</a>
					{% if not column.original %}
					<span class="glyphicon glyphicon-plus" data-toggle="tooltip" data-placement="top" title="Based on column {{column.based_on}}. Some databases have more than one value on the same column. Profiler automatically extract these nested columns into new columns to facilitate the analysis."></span>
					{% endif %}
				</td> 
				<td>{{ column.socrata_type|default:'' }}</td> 
				<td>{{ column.profiler_type|default:'' }}</td> 
				<td>{{ column.profiler_type_most_detected|default:'' }} 
					<span class="badge" data-toggle="tooltip" data-placement="right" title="Percentage of this type.">{{ column.profiler_type_most_detected_percent|floatformat }}%</span>
					
				</td> 
				<!-- <td>{{ column.unique_percent|floatformat }}%</td>  -->
				<td>{{ column.missing_percent|floatformat }}%</td> 
				<td>
					<a href="{% url 'finder:detail-database-column' db.database_id|escape_url column.name|escape_url %}"><span class="glyphicon glyphicon-search"></span></a>
				</td> 
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% endif %}
</div>
{% endif %}



<script>
$(function () {$('[data-toggle="tooltip"]').tooltip()})
$('.dropdown-toggle').dropdown()
</script>

data-finder-site/finder/templates/finder/includes/tab_related_datasets.html
{% load humanize %}
{% load finder_extras %}

<div class="panel-group" id="accordion">

	<!-- Same Category -->
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 class="panel-title"> <a href='#' data-toggle="collapse" data-target="#collapseOne">
				Same Category <b>({{datasets_with_same_category|length}})</b>
			</a></h4>
		</div>
		<div id="collapseOne" class="panel-collapse collapse">
			<div class="panel-body">
				{% if datasets_with_same_category %}
				<ul>
					{% for dataset in datasets_with_same_category %}
					<li> <a href='{% url 'finder:detail-database' db.database_id %}'>{{dataset.title}}</a> </li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
		</div>
	</div>

	<!-- Same Column Name -->
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 class="panel-title"> <a href='#' data-toggle="collapse" data-target="#collapseTwo">
				Same Column Name <b>({{datasets_with_same_column_name|length}})</b>
			</a></h4>
		</div>
		<div id="collapseTwo" class="panel-collapse collapse">
			<div class="panel-body">
				{% if datasets_with_same_column_name %}
				<table class="table table-striped table-hover tablesorter">
					<thead> <th>Dataset</th> <th>Column</th> </thead>

					{% for column in datasets_with_same_column_name %}
					<tr> 
						<td> <a href='{% url 'finder:detail-database' column.database.database_id %}'>{{column.database.title}}</a> </td> 
						<td> <a href="{% url 'finder:detail-database-column' column.database.database_id column.name %}">{{column.name}}</a> </td>
					</tr>
					{% endfor %}
				</table>
				{% endif %}
			</div>
		</div>
	</div>


	
</div> <!-- Close panel-group -->

<script>
//Close by default
$( document ).ready(function() { 
	$('.panel-collapse').collapse('hide');
	$('.panel-title').attr('data-toggle', 'collapse');
});
</script>

data-finder-site/finder/templates/finder/includes/timeline.html
{% load staticfiles %}
{% load humanize %}

<script src="{% static 'd3/d3.v3.js' %}"></script>
{# <script src="{% static 'finder/timeseries.js' %}"></script> #}
<script src="{% static 'metricsgraphics/metricsgraphics.js' %}"></script>

<div id='timeline-canvas'>
{# 	{% include "finder/includes/google_chart.html" with title='Records by Month' data_from=api_url|add:api_timeline_query id='timeline' width="'100%'" height="'100%'" type='area' options="{hAxis: { textPosition: 'none' }}"%} #}
<div id="div_area_chart_timeline" style="width:100%; height:100%"></div>
</div>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  // Load the Visualization API and the piechart package.
  google.load('visualization', '1.0', {'packages':['corechart']});
  // Set a callback to run when the Google Visualization API is loaded.
  google.setOnLoadCallback(fetch_timeline_data);
  $(window).on("throttledresize", function (event) {
    draw_timeline(context);
  });

  // Callback that creates and populates a data table,
  // instantiates the pie chart, passes in the data and
  // draws it.
  var context = {};

  function fetch_timeline_data() {
	{% url 'api:timeline-data' as api_url %}
  	var apiCall = "{{api_url|add:api_timeline_query|escapejs}}";
  	// console.log('cal api:' + apiCall);
    $.getJSON( apiCall, function( data ) { 

      // console.log('JSON CALL');
      // console.log(data);
      context.chart_data = data;
      if (data != null && data.length > 0 ){
        draw_timeline(context);
      }else{
        console.log('No data retrieved to plot timeline.');
      }
    });
  }

  function draw_timeline(context){
  	var chart_data = context.chart_data;
    // Set chart options
    var options = {
      'title':'Timeline',
      'is3D': true,
      'titleTextStyle': {fontSize: 15, bold: true},
      // animation:{
      //     duration: 1000,
      //     easing: 'out',
      //   },
      //This chart
      chartArea: {width: "100%"},
      hAxis: {
            format: 'MMM, yyyy',
            gridlines: {
            			count: -1,
            			units: {
            			    years: {format: ['yyyy']},
            			  }
            			}
          },
        vAxis: { gridlines: { count: 2},
        },
    	legend: {position:'none'},
    	maxTextLines: 1,
    	explorer: { axis: 'horizontal', keepInBounds: true, maxZoomOut: 1 },
    	// legend: {position: 'top'},
    };
    
    // Instantiate and draw our chart, passing in some options.
    var chart_div = document.getElementById("div_area_chart_timeline");
    var chart = null;
    var data = null;
      
	chart_data = [['Month-Year', "Records"]].concat(chart_data);

	//Prepare data as Date
	for (var i in chart_data){
		// console.log(chart_data[i]);
		from = chart_data[i][0].split('-')
		chart_data[i][0] = new Date(from[0], from[1]-1);
		// console.log(chart_data[i]);
	}

  chart = new google.visualization.AreaChart( chart_div );
	// chart = new google.visualization.ColumnChart( chart_div );
	chart.draw(new google.visualization.DataTable(), options);
	data = new google.visualization.arrayToDataTable( chart_data );
	var monthYearFormatter = new google.visualization.DateFormat({ pattern: "MMM yyyy" });
	monthYearFormatter.format(data, 0);
    chart.draw(data, options);
  }

  function prepareColors(data, colors){
    if (colors != null){
      data[0][data[0].length] = { role: 'style' }

      for (i = 1; i < data.length; i++) { 
        data[i][data[i].length] = colors[i-1];
      }
    }
    return data
  }
  </script>